In [27]:
import pandas as pd

In [28]:
df_2009 = pd.read_csv("microdados_2009_limpo.csv", sep=";", encoding="latin-1")
df_2013 = pd.read_csv("microdados_2013_limpo.csv", sep=";", encoding="latin-1")
df_2016 = pd.read_csv("microdados_2016_limpo.csv", sep=";", encoding="latin-1")
df_2020 = pd.read_csv("microdados_2020_limpo.csv", sep=",", encoding="latin-1")
df_2021 = pd.read_csv("microdados_2021_limpo.csv", sep=",", encoding="latin-1")
df_2022 = pd.read_csv("microdados_2022_limpo.csv", sep=",", encoding="latin-1")

dfs = [df_2009, df_2013, df_2016, df_2020, df_2021, df_2022]

In [29]:
colunas_comuns = [col for col in df_2009.columns if all(col in df.columns for df in dfs)]

In [30]:
colunas_exclusivas = []
for df in dfs:
    for col in df.columns:
        if col not in colunas_comuns and col not in colunas_exclusivas:
            colunas_exclusivas.append(col)

In [31]:
ordem_final = colunas_comuns + colunas_exclusivas

In [32]:
df_unificado = pd.concat(dfs, ignore_index=True)
df_unificado = df_unificado[ordem_final]

In [33]:
df_unificado.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ST_CONCLUSAO,SG_UF_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,TP_COR_RACA,Q001,Q002,Q006,TP_ESCOLA,Q003,Q004
0,2009,5,F,1.0,RJ,459.6,410.4,536.6,556.9,575.0,A,B,E,B,NaN,NaN,NaN
1,2009,9,F,4.0,RJ,406.9,430.3,519.9,413.1,500.0,B,B,B,B,NaN,NaN,NaN
2,2009,7,F,1.0,RJ,432.3,527.7,541.2,464.4,700.0,B,C,F,C,NaN,NaN,NaN
3,2009,3,F,2.0,RJ,406.1,629.9,580.0,417.9,775.0,C,C,C,B,NaN,NaN,NaN
4,2009,11,F,1.0,RJ,430.8,424.6,457.8,560.3,625.0,A,C,C,C,NaN,NaN,NaN

In [34]:
df_unificado.tail()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ST_CONCLUSAO,SG_UF_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,TP_COR_RACA,Q001,Q002,Q006,TP_ESCOLA,Q003,Q004
16478192,2022,12,M,1.0,PA,444.5,504.4,489.5,423.6,580.0,1,E,E,C,1.0,C,C
16478193,2022,11,F,1.0,SP,536.1,633.2,584.0,596.3,740.0,2,H,C,D,1.0,F,C
16478194,2022,2,M,2.0,MG,487.6,495.6,545.5,597.4,580.0,3,H,E,B,2.0,C,B
16478195,2022,11,F,1.0,PR,512.5,524.8,546.8,432.0,520.0,1,C,B,B,1.0,B,B
16478196,2022,2,M,2.0,SC,527.9,627.0,583.3,637.1,660.0,1,E,C,G,2.0,C,B