In [1]:
import pandas as pd

In [2]:
ANO = 2009
arquivo_microdados = f"MICRODADOS_ENEM_{ANO}.csv"

In [3]:
colunas_microdados = ["TP_SEXO", "Q3", "TP_FAIXA_ETARIA", "SG_UF_PROVA",
            "TP_ST_CONCLUSAO", "NU_ANO", "Q17", "Q18", "Q21", "NU_NOTA_CN", "NU_NOTA_CH", "NU_NOTA_LC", "NU_NOTA_MT", "NU_NOTA_REDACAO"]

In [4]:
microdados = pd.read_csv(arquivo_microdados, sep=";", encoding="latin-1", usecols=colunas_microdados)

C:\Users\hugos\AppData\Local\Temp\ipykernel_19692\2144925095.py:1: DtypeWarning: Columns (48: Q3, 62: Q17, 63: Q18, 66: Q21) have mixed types. Specify dtype option on import or set low_memory=False.
  microdados = pd.read_csv(arquivo_microdados, sep=";", encoding="latin-1", usecols=colunas_microdados)

In [5]:
microdados.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ST_CONCLUSAO,SG_UF_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q3,Q17,Q18,Q21
0,2009,5,F,1.0,RJ,459.6,410.4,536.6,556.9,575,A,B,E,B
1,2009,4,M,2.0,RJ,409.2,323.1,376.7,360.5,475,NaN,NaN,NaN,NaN
2,2009,9,F,4.0,RJ,406.9,430.3,519.9,413.1,500,B,B,B,B
3,2009,7,F,1.0,RJ,432.3,527.7,541.2,464.4,700,B,C,F,C
4,2009,3,F,2.0,RJ,406.1,629.9,580.0,417.9,775,C,C,C,B

In [6]:
microdados_limpos = microdados.dropna()

In [7]:
microdados_limpos.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ST_CONCLUSAO,SG_UF_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,Q3,Q17,Q18,Q21
0,2009,5,F,1.0,RJ,459.6,410.4,536.6,556.9,575,A,B,E,B
2,2009,9,F,4.0,RJ,406.9,430.3,519.9,413.1,500,B,B,B,B
3,2009,7,F,1.0,RJ,432.3,527.7,541.2,464.4,700,B,C,F,C
4,2009,3,F,2.0,RJ,406.1,629.9,580.0,417.9,775,C,C,C,B
5,2009,11,F,1.0,RJ,430.8,424.6,457.8,560.3,625,A,C,C,C

In [8]:
microdados_limpos = microdados_limpos.rename(columns={
    "Q3" : "TP_COR_RACA",
    "Q17" : "Q001",
    "Q18" : "Q002",
    "Q21" : "Q006"
    
})

In [9]:
microdados_limpos.head()

,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ST_CONCLUSAO,SG_UF_PROVA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,TP_COR_RACA,Q001,Q002,Q006
0,2009,5,F,1.0,RJ,459.6,410.4,536.6,556.9,575,A,B,E,B
2,2009,9,F,4.0,RJ,406.9,430.3,519.9,413.1,500,B,B,B,B
3,2009,7,F,1.0,RJ,432.3,527.7,541.2,464.4,700,B,C,F,C
4,2009,3,F,2.0,RJ,406.1,629.9,580.0,417.9,775,C,C,C,B
5,2009,11,F,1.0,RJ,430.8,424.6,457.8,560.3,625,A,C,C,C

In [10]:
microdados_limpos.to_csv(f"microdados_{ANO}_limpo.csv", sep=";", encoding="latin-1", index=False)